[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.setuptools"]

[phases.install]
cmds = ["pip3 install --upgrade pip", "pip3 install -r requirements.txt"]

[start]
cmd = "python3 bot.py"

